In [1]:
import numpy as np

In [2]:
n = 6
E = [(0, 1), (0, 2), (1, 2), (2, 3), (2, 4), (4, 5)]
A = np.zeros((n, n))
for (i, j) in E:
    A[i, j] = A[j, i] = 1
print(A)

[[0. 1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]]


# (fixed) 特徴と重み

In [3]:
X = np.array([
    [0, 0, 0], # 0
    [0, 0, 1], # 1
    [0, 1, 0], # 2
    [0, 1, 1], # 3
    [1, 0, 0], # 4
    [1, 1, 0], # 5
])
d = X.shape[1]
out_dim = 2

W = np.ones((d, out_dim))

## another example
# W = np.array([[0, 1], [2, 3], [4, 5]])

print(X)
print(W)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


# 式の計算

In [4]:
Ahat = A + np.eye(n)
Dhat = lambda x: np.diag(np.power(np.sum(Ahat, axis=1), x))
D = np.diag(np.power(np.sum(Ahat, axis=1), -1))

In [5]:
mat0 = Ahat @ X @ W # none
mat2 = (Dhat(-1/2)) @ Ahat @ (Dhat(-1/2)) @ X @ W # both
print(mat0)
print(mat2)

[[2. 2.]
 [2. 2.]
 [5. 5.]
 [3. 3.]
 [4. 4.]
 [3. 3.]]
[[0.59153222 0.59153222]
 [0.59153222 0.59153222]
 [1.34885331 1.34885331]
 [1.31622777 1.31622777]
 [1.4080288  1.4080288 ]
 [1.40824829 1.40824829]]
